workflows:
  vorxy-vpn:
    name: Vorxy VPN
    max_build_duration: 60
    environment:
      flutter: 3.47.1
    scripts:
      - name: Create MainActivity
        script: |
          mkdir -p android/app/src/main/kotlin/com/vorxy/vpn
          cat > android/app/src/main/kotlin/com/vorxy/vpn/MainActivity.kt << 'EOF'
          package com.vorxy.vpn
          import io.flutter.embedding.android.FlutterActivity
          class MainActivity: FlutterActivity()
          EOF
      - name: Clean build
        script: |
          rm -rf build
          rm -rf .dart_tool
          rm -rf android/.gradle
          rm -rf android/app/build
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
