name: vorxy_vpn
description: Vorxy VPN - Free Unlimited VPN
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.4.0
  shared_preferences: ^2.6.0
  connectivity_plus: ^6.2.0
  permission_handler: ^12.0.1
  flutter_v2ray: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
